name: CI

on: 
  workflow_dispatch:
  push:
    branches:
    - main
env:
  IMAGE_TAG: "123"
  CONTAINER_APP_URL: "https://tsvi.io"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
      issues: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    
    - name: Create an artifact
      id: artifact
      run: echo "Test" >> test.txt
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: test.txt

    - name: Wait for artifact to be available
      run: sleep 60

    - name: Fetch Artifact ID
      id: fetch-artifact-id
      run: |
        echo "Fetching Artifact ID..."
        for i in {1..5}; do
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts)
          echo "API Response: $RESPONSE"
          ARTIFACT_ID=$(echo "$RESPONSE" | jq -r '.artifacts[] | select(.name=="artifact") | .id')
          if [ -n "$ARTIFACT_ID" ]; then
            echo "ARTIFACT_ID = $ARTIFACT_ID"
            echo "artifact_id=$ARTIFACT_ID" >> $GITHUB_ENV
            break
          else
            echo "Artifact not found, retrying in 10 seconds..."
            sleep 10
          fi
        done

    - name: Debug Artifact ID
      run: "echo Debugging Artifact ID: ${{ env.artifact_id }}"

    # - name: Generate Artifact URL
    #   id: generate_artifact_url
    #   run: |
    #     sleep 60
    #     ARTIFACT_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts | jq -r '.artifacts[] | select(.name=="artifact") | .id')
    #     echo "ARTIFACT_ID = $ARTIFACT_ID"
    #     echo "ARTIFACT_URL=https://github.com/tsviz/actions-test/actions/runs/${{ github.run_id }}/artifacts/${ARTIFACT_ID}" >> $GITHUB_ENV
  
    - name: Create Issue
      uses: actions/github-script@v3
      with:
        script: |
          const issueTemplate = `
          ### Staging Environment Ready for Testing
          
          The staging environment is ready for testing. Please verify that the following items are working as expected:
          
          - [ ] The staging environment is up and running
          - [ ] The staging environment is accessible
          - [ ] The staging environment is using the correct image tag
          - [ ] The staging environment is using the correct database schema
          
          Additional Information:
          - Image Tag: ${process.env.IMAGE_TAG}
          - Server URL: ${process.env.CONTAINER_APP_URL}
          - Terraform IaC files - Artifact URL: ${process.env.ARTIFACT_URL}
          `;
          
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Staging Environment Ready for Testing",
            body: issueTemplate,
            labels: ["staging", "ready-for-testing"],
            assignees: ["tsviz"]
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        CONTAINER_APP_URL: ${{ env.CONTAINER_APP_URL }}
        ARTIFACT_URL: ${{ env.ARTIFACT_URL }}