name: CI

on: 
  workflow_dispatch:
  push:
    branches:
    - main
env:
  IMAGE_TAG: "123"
  CONTAINER_APP_URL: "https://tsvi.io"
  ARTIFACT_URL: "https://tsvi.io/artifact"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
      issues: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Create Issue
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        CONTAINER_APP_URL: ${{ env.CONTAINER_APP_URL }}
        ARTIFACT_URL: ${{ env.ARTIFACT_URL }}    
      with:
        filename: .github/ISSUE_TEMPLATE/staging-environment-ready.md
        assignees: tsviz
    
    # - name: Create Issue
    #   uses: peter-evans/create-issue-from-file@v5.0.1
    #   with:
    #     title: Staging Environment Ready for Testing
    #     labels: staging,ready-for-testing,UAT
    #     assignees: ${{ github.actor }}
    #     content-filepath: .github/ISSUE_TEMPLATE/staging-environment-ready.md
