name: CI

on: 
  workflow_dispatch:
  push:
    branches:
    - main
env:
  IMAGE_TAG: "123"
  CONTAINER_APP_URL: "https://tsvi.io"
  ARTIFACT_URL: "https://tsvi.io/artifact"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    permissions:
      actions: read
      contents: read
      packages: write
      id-token: write
      issues: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7
    
    - name: Create Issue
      uses: actions/github-script@v3
      with:
        script: |
          const issueTemplate = `
          ### Staging Environment Ready for Testing
          
          The staging environment is ready for testing. Please verify that the following items are working as expected:
          
          - [ ] The staging environment is up and running
          - [ ] The staging environment is accessible
          - [ ] The staging environment is using the correct image tag
          - [ ] The staging environment is using the correct database schema
          
          Additional Information:
          - Image Tag: ${process.env.IMAGE_TAG}
          - Server URL: ${process.env.CONTAINER_APP_URL}
          - Terraform IaC files - Artifact URL: ${process.env.ARTIFACT_URL}
          `;
          
          github.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: "Staging Environment Ready for Testing",
            body: issueTemplate,
            labels: ["staging", "ready-for-testing"],
            assignees: ["tsviz"]
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
        CONTAINER_APP_URL: ${{ env.CONTAINER_APP_URL }}
        ARTIFACT_URL: ${{ env.ARTIFACT_URL }}
    # - name: Create Issue
    #   uses: JasonEtco/create-an-issue@v2
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     IMAGE_TAG: ${{ env.IMAGE_TAG }}
    #     CONTAINER_APP_URL: ${{ env.CONTAINER_APP_URL }}
    #     ARTIFACT_URL: ${{ env.ARTIFACT_URL }}    
    #   with:
    #     filename: .github/ISSUE_TEMPLATE/staging-environment-ready.md
    #     assignees: tsviz
    
    # - name: Create Issue
    #   uses: peter-evans/create-issue-from-file@v5.0.1
    #   with:
    #     title: Staging Environment Ready for Testing
    #     labels: staging,ready-for-testing,UAT
    #     assignees: ${{ github.actor }}
    #     content-filepath: .github/ISSUE_TEMPLATE/staging-environment-ready.md
