name: Build on Issue Closed

on:
  issues:
    types: [closed]

jobs:
  build:
    if: contains(github.event.issue.labels.*.name, 'staging')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Extract Artifact URL
      id: extract-url
      run: |
        echo "Extracting Artifact URL from issue body..."
        ARTIFACT_URL=$(echo "${{ github.event.issue.body }}" | grep -oP 'Artifact URL:\s*\K\S+')
        echo "artifact_url=${ARTIFACT_URL}" >> $GITHUB_ENV

    - name: Use Artifact URL
      run: "echo Using Artifact URL: ${{ env.artifact_url }}"